### ISSUE TITLE
fails to build on OS X 10.11.5

### ISSUE THREAD

**Issue by loganrosen** [rocasa/ttylog#6]
I was trying to update the formula for ttylog in Homebrew, but version 0.29 fails to build for me on OS X 10.11.5. Here's the relevant build output:

<pre>[ 50%] Building C object CMakeFiles/ttylog.dir/ttylog.c.o
/usr/local/Library/ENV/4.3/clang   -I/tmp/ttylog-20160626-58659-1q8men5/ttylog-0.29 -I/tmp/ttylog-20160626-58659-1q8men5/ttylog-0.29/build  -Wall -O2 -DNDEBUG   -o CMakeFiles/ttylog.dir/ttylog.c.o   -c /tmp/ttylog-20160626-58659-1q8men5/ttylog-0.29/ttylog.c
/tmp/ttylog-20160626-58659-1q8men5/ttylog-0.29/ttylog.c:52:3: error: unknown type name 'timer_t'; did you mean 'time_t'?
  timer_t timerid;
  ^~~~~~~
  time_t
/usr/include/sys/_types/_time_t.h:30:26: note: 'time_t' declared here
typedef __darwin_time_t         time_t; 
                                ^
/tmp/ttylog-20160626-58659-1q8men5/ttylog-0.29/ttylog.c:135:27: error: use of undeclared identifier 'CLOCK_REALTIME'
        if (timer_create (CLOCK_REALTIME, &sevp, &timerid) == -1)
                          ^
/tmp/ttylog-20160626-58659-1q8men5/ttylog-0.29/ttylog.c:140:27: error: variable has incomplete type 'struct itimerspec'
        struct itimerspec new_value;
                          ^
/tmp/ttylog-20160626-58659-1q8men5/ttylog-0.29/ttylog.c:140:16: note: forward declaration of 'struct itimerspec'
        struct itimerspec new_value;
               ^
3 errors generated.
make[2]: *** [CMakeFiles/ttylog.dir/ttylog.c.o] Error 1
make[1]: *** [CMakeFiles/ttylog.dir/all] Error 2
make: *** [all] Error 2</pre>

**Comment by jame** [comment]
Yes, that's in the functionality for the *-t* (--timeout) option that was added with version 0.27.  You kindly provided a way to better handle 'librt' for OS X but that is used by the *-t* option so that will not be usable on OS X until a way can be found to implement the same functionality.

**Comment by jame** [comment]
See also https://sourceforge.net/p/ttylog/bugs/9/.

**Comment by jame** [comment]
A work around in the code for now could be to bypass the '-t' option altogether when compiling on OS X (or anywhere else where that library is not available). Perhaps enclosing the code for the '-t' option with an 'if' clause that just prints something like that the '-t' option is not available when the librt library is not available.
